// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy6uUdwzg3OuGEMWhQVsfHQVSR2irdDL0',
    appId: '1:1061208534442:web:636dabcc9c1810cbe10fd3',
    messagingSenderId: '1061208534442',
    projectId: 'confidentvoiceapp',
    authDomain: 'confidentvoiceapp.firebaseapp.com',
    storageBucket: 'confidentvoiceapp.firebasestorage.app',
    measurementId: 'G-E1R27T6V3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQs7EnOnVJ-iT_hLIqjjIQu7naEzBwBjQ',
    appId: '1:1061208534442:android:8e25e125c76d291ae10fd3',
    messagingSenderId: '1061208534442',
    projectId: 'confidentvoiceapp',
    storageBucket: 'confidentvoiceapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW44ie3Wt-jv46y2E7cvRipOLdU9u4AXM',
    appId: '1:1061208534442:ios:d274d3e2fa257292e10fd3',
    messagingSenderId: '1061208534442',
    projectId: 'confidentvoiceapp',
    storageBucket: 'confidentvoiceapp.firebasestorage.app',
    iosBundleId: 'com.example.hadilTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW44ie3Wt-jv46y2E7cvRipOLdU9u4AXM',
    appId: '1:1061208534442:ios:d274d3e2fa257292e10fd3',
    messagingSenderId: '1061208534442',
    projectId: 'confidentvoiceapp',
    storageBucket: 'confidentvoiceapp.firebasestorage.app',
    iosBundleId: 'com.example.hadilTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy6uUdwzg3OuGEMWhQVsfHQVSR2irdDL0',
    appId: '1:1061208534442:web:a227e6172c18e38ee10fd3',
    messagingSenderId: '1061208534442',
    projectId: 'confidentvoiceapp',
    authDomain: 'confidentvoiceapp.firebaseapp.com',
    storageBucket: 'confidentvoiceapp.firebasestorage.app',
    measurementId: 'G-F7SWPRRC9Y',
  );
}
